### PR TITLE
Change work_start/work_end params to time(0) DT

### PR DESCRIPTION
**Pull request by ben-thul**
(Copied from #345, but this time dev → dev)

From the brief "discussion" that we had on [your blog post](https://erikdarling.com/sp_quickiestore-find-your-worst-performing-queries-during-working-hours/), here's my swing at changing the DT for work start/end to `time`.

While going through it, I had to change how the where clause was constructed in the case where local working hours span midnight UTC. Left a perhaps overly verbose comment as to my reasoning and an example inline with the code.

### CODE REVIEW

**Comment by ben-thul** [comment]
you-got-it-dude.gif

**Comment by erikdarlingdata** [comment]
@ben-thul something funky is going on with your code changes! Real funky. Superfunky.

I'm pulling out the relevant chunks, and I'll add screenshots to show how things end up on my instance.

```
DECLARE
    @work_start_utc time(0) = '9am',
    @work_end_utc time(0) = '5pm',
    @utc_minutes_difference bigint =
        DATEDIFF
        (
            MINUTE,
            SYSDATETIME(),
            SYSUTCDATETIME()
        );

SELECT
    sys_date_time = SYSDATETIME(),
    work_start_utc = @work_start_utc,
    work_end_utc = @work_end_utc,
    utc_minutes_difference = @utc_minutes_difference;

SELECT
    @work_start_utc =
        DATEADD
        (
            MINUTE,
            @utc_minutes_difference,
            @work_start_utc
        ),
    @work_end_utc =
        DATEADD
        (
            MINUTE,
            @utc_minutes_difference,
            @work_end_utc
        );

SELECT
    work_start_utc =
        DATEADD
        (
            MINUTE,
            @utc_minutes_difference,
            @work_start_utc
        ),
    work_end_utc =
        DATEADD
        (
            MINUTE,
            @utc_minutes_difference,
            @work_end_utc
        );
```

image

When I run your version, I get no results back. When I run the original version, I get a bunch of stuff back.

```
EXEC sp_QuickieStore 
    @workdays = 1, 
    @debug = 1, 
    @start_date = '20231201';
```

Yours ends up using the alternate where clause:

```
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT TOP (@top)
    qsrs.plan_id
FROM [StackOverflow2013].sys.query_store_runtime_stats AS qsrs
WHERE 1 = 1
AND   qsrs.last_execution_time >= @start_date
AND   qsrs.last_execution_time <  @end_date
AND   DATEPART(WEEKDAY, qsrs.last_execution_time) BETWEEN 2 AND 6
AND  
(
       CAST(qsrs.last_execution_time as time(0)) BETWEEN @work_start_utc AND '00:00' 
    OR CAST(qsrs.last_execution_time as time(0)) BETWEEN '00:00' AND @work_end_utc
)
AND   NOT EXISTS
      (
          SELECT
              1/0
          FROM #maintenance_plans AS mp
          WHERE mp.plan_id = qsrs.plan_id
      )
GROUP
    BY qsrs.plan_id
ORDER BY
    MAX(qsrs.avg_cpu_time) DESC
OPTION(RECOMPILE, OPTIMIZE FOR (@top = 9223372036854775807));
```

**Comment by ben-thul** [comment]
I'll take a look (and it looks like you're testing somewhere that is on PST which makes out conversation easier). But at first glance, having work_start_utc = 01:00 and work_end_utc = 09:00 shouldn't qualify for the alternate WHERE clause (since start < end). Though, even if it does, that doesn't explain why you get nothing back. Like... you should end up with something like this (paraphrased):

```sql
WHERE
   (last_execution_time between '01:00' and '00:00')
   or (last_execution_time between '00:00' and '09:00')
```

Which, the first predicate is nonsense but the second should get you stuff (and, coincidentally, includes the 01:00-09:00 interval).

**Comment by erikdarlingdata** [comment]
@ben-thul heh yeah, all my windows server VMs are PST for some dumb default reason. anyway, let me know how things end up.

**Comment by ben-thul** [comment]
I found the issue and it's because the time DT is, ahem, a little less sophisticated than I thought. 

Pop quiz: is 23:59
- before midnight
- after midnight

Of course, the answer is "yes" (it's after midnight of day one, before midnight of day two). But the _real_ answer is that without the context of a day, you have to have an opinionated choice. and in the case of the time DT, it chooses ~violence~ _after_ midnight. So boo me. I think I have a reasonable fix though. Stand by for incoming PR.

**Pull request merged**
