### PR TITLE
Update sp_QuickieStore.sql

### LINKED ISSUE #391: My favorite [sp_QuickieStore] is giving an error when used with Azure SQL Database
**Is your feature request related to a problem? Please describe.**
I am big fan of you, however, when I had to work on Azure SQL DB, the sp_QuickieStore gives an error

Error:
Msg 208, Level 16, State 1, Procedure sp_QuickieStore, Line 1133 [Batch Start Line 0]
Invalid object name 'sys.dm_hadr_availability_replica_states'.

**Describe the solution you'd like**
Declare one more Variable , say, @azurecheck and bypass the original logic of  if we are in Azure SQL DB.

Original Code which gives error
AND   NOT EXISTS
(
    SELECT 
        1/0
    FROM sys.dm_hadr_availability_replica_states AS s
    JOIN sys.availability_databases_cluster AS c
      ON  s.group_id = c.group_id 
      AND d.name = c.database_name
    WHERE s.is_local <> 1
    AND   s.role_desc <> N'PRIMARY'
    AND   DATABASEPROPERTYEX(c.database_name, N'Updateability') <> N'READ_WRITE'
)

**Describe alternatives you've considered**
I have modified the  original code to this for Azure SQL DB

IF @azure = 1
BEGIN
    -- Logic specific to Azure SQL Database
    INSERT INTO #databases WITH(TABLOCK)
    (
        database_name
    )
    SELECT
        database_name = ISNULL(@database_name, DB_NAME())
    WHERE @get_all_databases = 0

    UNION ALL

    SELECT
        database_name = d.name
    FROM sys.databases AS d
    WHERE @get_all_databases = 1
    AND d.is_query_store_on = 1
    AND d.database_id > 4
    AND d.state = 0 
    AND d.is_in_standby = 0 
    AND d.is_read_only = 0
    OPTION(RECOMPILE);
END
ELSE
BEGIN
    -
    INSERT INTO #databases WITH(TABLOCK)
    (
        database_name
    )
    SELECT
        database_name = ISNULL(@database_name, DB_NAME())
    WHERE @get_all_databases = 0

    UNION ALL

    SELECT
        database_name = d.name
    FROM sys.databases AS d
    WHERE @get_all_databases = 1
    AND d.is_query_store_on = 1
    AND d.database_id > 4
    AND d.state = 0 
    AND d.is_in_standby = 0 
    AND d.is_read_only = 0
    AND NOT EXISTS
    (
        SELECT 1/0
        FROM sys.dm_hadr_availability_replica_states AS s
        JOIN sys.availability_databases_cluster AS c
          ON s.group_id = c.group_id 
          AND d.name = c.database_name
        WHERE s.is_local <> 1
        AND s.role_desc <> N'PRIMARY'
        AND DATABASEPROPERTYEX(c.database_name, N'Updateability') <> N'READ_WRITE'
    )
    OPTION(RECOMPILE);
	END

**Are you ready to build the code for the feature?**
Yes.

### PR DESCRIPTION
**Pull request by erikdarlingdata**
Closes #391

@AbhinavTiwariDBA can you test this code out before I push to main?

I think I'm going to have to tweak it some in the future to deal with secondaries in Managed Instance, but I don't have any of those available to test on. As long as it works in SQLDB for now, that's good enough. Thanks again for reporting this, and making the initial pull request!

### CODE REVIEW

**Review by AbhinavTiwariDBA — APPROVED** [review]
There is one more block of code which gives this error

Msg 208, Level 16, State 1, Procedure sp_QuickieStore, Line 2259 [Batch Start Line 0]
Invalid object name 'sys.availability_groups'.



Correct Code can be
--------------------------------------------------------------------
/*
See if AGs are a thing so we can skip the checks for replica stuff
*/
IF (SELECT CONVERT(int, SERVERPROPERTY('EngineEdition'))) NOT IN (5, 8)
BEGIN
    -- Code specific to SQL Server
    -- This part can safely reference sys.availability_groups
    SELECT
        @ags_present =
            CASE
                WHEN EXISTS
                     (
                         SELECT 1
                         FROM sys.availability_groups AS ag
                     )
                THEN 1
                ELSE 0
            END
        OPTION(RECOMPILE);
END
ELSE
BEGIN
    -- Code specific to Azure SQL Database
    -- Do not reference sys.availability_groups here
    SELECT
        @ags_present = 0;
END;

**Review by AbhinavTiwariDBA — CHANGES_REQUESTED** [review]
The code still goes to else block

**Comment by erikdarlingdata** [comment]
@AbhinavTiwariDBA thanks for that! added the check in. Let me know if there's anything else.

**Comment by AbhinavTiwariDBA** [comment]
Thanks, Erik! However, the updated code in the DEV branch is encountering a random syntax error. I'm attaching a code that runs smoothly without any issues. This code is copied from the main branch; I only modified it for Azure SQL DB(with same code which you changed in DEV), and it works flawlessly.

[sp_QuickieStore.txt](https://github.com/erikdarlingdata/DarlingData/files/14839168/sp_QuickieStore.txt)


Error in DEV branch code (Looks like an extra comma but not sure)
--------------------------------------

Msg 50000, Level 11, State 1, Procedure dbo.sp_QuickieStore, Line 8207 [Batch Start Line 0]
error while inserting #query_store_plan with @expert mode = 1 and format_output = 1
offending query:

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT
    @database_id,
    qsp.plan_id,
    qsp.query_id,
    all_plan_ids =
        STUFF
        (
            (
                SELECT DISTINCT
                    ', ' +
                    RTRIM
                        (qsp_plans.plan_id)
                FROM [free-database-azure-sql].sys.query_store_plan AS qsp_plans
                WHERE qsp_plans.query_id = qsp.query_id
                FOR XML PATH(''), TYPE
            ).value('./text()[1]', 'varchar(max)'),
            1,
            2,
            ''
        ),
    qsp.plan_group_id,
    qsp.engine_version,
    qsp.compatibility_level,
    qsp.query_plan_hash,
    qsp.query_plan,
    qsp.is_online_index_plan,
    qsp.is_trivial_plan,
    qsp.is_parallel_plan,
    qsp.is_forced_plan,
    qsp.is_natively_compiled,
    qsp.force_failure_count,
    qsp.last_force_failure_reason_desc,
    qsp.count_compiles,
    qsp.initial_compile_start_time,
    qsp.last_compile_start_time,
    qsp.last_execution_time,
    (qsp.avg_compile_duration / 1000.),
    (qsp.last_compile_duration / 1000.),
FROM #query_store_runtime_stats AS qsrs
CROSS APPLY
(
    SELECT TOP (@plans_top)
        qsp.*
    FROM [free-database-azure-sql].sys.query_store_plan AS qsp
    WHERE qsp.plan_id = qsrs.plan_id
    AND   qsp.is_online_index_plan = 0
    ORDER BY
        qsp.last_execution_time DESC
) AS qsp
WHERE qsrs.database_id = @database_id
OPTION(RECOMPILE, OPTIMIZE FOR (@plans_top = 9223372036854775807));

Msg 156, Level 15, State 1, Line 42
Incorrect syntax near the keyword 'FROM'.

**Comment by erikdarlingdata** [comment]
@AbhinavTiwariDBA yep, I see what happened. I've updated the dev branch -- can you give that a shot now?

**Comment by AbhinavTiwariDBA** [comment]
Now its perfect, thanks. Working !!

**Review by AbhinavTiwariDBA — APPROVED** [review]
Working.

**Comment by erikdarlingdata** [comment]
@AbhinavTiwariDBA great, thanks for working through that with me. I've merged into main.

**Pull request merged**
