### PR TITLE
sp_QuickieStore: Added ability to check for regressions.

### LINKED ISSUE #448: sp_QuickieStore: Add a way to check for queries that have recently changed in performance
**Is your feature request related to a problem? Please describe.**
This is absolutely something that I would use. I frequently use Query Store to check how my instance/database/query has changed since I made a change. This kind of A-B testing is even [one of the suggested use cases for Query Store](https://learn.microsoft.com/en-us/sql/relational-databases/performance/query-store-usage-scenarios?view=sql-server-ver16#ab-testing) and there are [two](https://learn.microsoft.com/en-us/sql/relational-databases/performance/tune-performance-with-the-query-store?view=sql-server-ver16#queries-that-recently-regressed-in-performance) [examples](https://learn.microsoft.com/en-us/sql/relational-databases/performance/tune-performance-with-the-query-store?view=sql-server-ver16#queries-with-historical-regression-in-performance) in the official docs and [one dashboard in SSMS](https://learn.microsoft.com/en-us/sql/relational-databases/performance/monitoring-performance-by-using-the-query-store?view=sql-server-ver16#Regressed) for it. Microsoft clearly want you to use Query Store for this and there is no greater pleasure than turning this data in to an argument-winning slideshow. Given that Erik is a consultant himself, I'm sure that he knows this very well... Along with the copy and pasting to Excel that it brings.

To my knowledge, `sp_QuickieStore` does not support this at all. If I want to use `sp_QuickieStore` to find queries that have recently changed in performance, I have to conduct awful hack like this:

1. Make a note of when I made the change that I want data about.
2. Search `sys.query_store_plan` for any queries that have at least two plans and have one that compiled after I made that change. Be super careful with what time I'm using for `initial_compile_start_time` because it doesn't handle UTC as gracefully as `sp_QuickieStore`.
3. Use `STRING_AGG` to turn the `query_id`s in to a comma separated list.
4. Call `sp_QuickieStore` with my `STRING_AGG` list as the `@include_query_ids` parameter and `@start_date` at the earliest point in time that I want to compare my new data against.

**Describe the solution you'd like**
Somehow, make `sp_QuickieStore` able to find queries that have changed in performance since a particular point in time. If I can hack it in and Microsoft can do it from the Query Store DMVs, then there must be a way to build in to to `sp_QuickieStore`.

**Describe alternatives you've considered**
Continue using my hacks, but beg for them to be added to the examples file.

**Are you ready to build the code for the feature?**
Yes... But it wouldn't be quick. I think I'd have to properly go line-by-line through `sp_QuickieStore` and really learn how it works before I can develop this one.

**IMPORTANT: If you're going to contribute code, please read the contributing guide first.**
https://github.com/erikdarlingdata/DarlingData/blob/main/CONTRIBUTING.md
Absolutely yes.

### PR DESCRIPTION
**Pull request by ReeceGoding**
At long last, closes #448 .

Is there still a ban on updating the documentation? I remember not being told to do that a while ago because Erik had big plans for it. Particularly with this change, the functionality of `sp_QuickieStore` will be far ahead of the docs. This is too big to go undocumented. It also merits examples in the examples file.

### CODE REVIEW

**Comment by erikdarlingdata** [comment]
@ReeceGoding I will review this now that I'm back at home. It generally looks good, I think aside from some [formatting oddities](https://github.com/erikdarlingdata/DarlingData/pull/486/files#diff-062e842a09d074e6ea95310f6b9e70e40292b8ebc8b1b3b8e02e7dc40d72734dR6403), but don't worry about those. 

My primary concern is that normal functionality works (well, let's just say "as it worked before") without the new functionality interfering. It looks like there are a couple spots where they interweave a little bit. How much testing have you done with normal operating stuff alongside the new regression stuff?

Also, sort of cool, QuickieStore is now > 10k lines of code, ha ha ha.

**Comment by erikdarlingdata** [comment]
@ReeceGoding I don't expect you to test all 48 parameters, just perhaps some common ones/ones in the examples file if possible. Anyway, it looks good to me in general (thanks for the second round of changes). I'll let this hang out for about a week to see if you find anything else in there you want to tweak before merging. I'm also holding off on some other changes until this goes in. 

To answer your other question, I don't have any sort of embargo on updating the docs or anything. If you're going to add the new parameters in, just a. make sure the help section is updated with them and b) run with help = 1 to get table output. When you have that, use this website: https://ozh.github.io/ascii-tables/ to make the table, but remember to set the output style to GitHub Markdown first. 

Thanks!

**Comment by ReeceGoding** [comment]
@erikdarlingdata Thanks Erik. I'll run through the examples file when I get a chance and update both it and the documentation. If it's not this weekend, then it'll be at some point next week. I'm currently low on free time.

**Comment by ReeceGoding** [comment]
@erikdarlingdata I've tested against everything currently in the examples file, except for the 2022-exclusive stuff. Aside from stuff that we expect to change like `@debug = 1`, all of the outputs from the code given are identical now to what they were previously on the box that I tested on. However, note that [not all of the parameters are in the example file](https://github.com/erikdarlingdata/DarlingData/issues/489).

I still need to add the new parameters to the readme and examples file.

**Comment by erikdarlingdata** [comment]
@ReeceGoding does that mean you're comfortable with merging this one in?

**Comment by ReeceGoding** [comment]
@erikdarlingdata I think I best update the documentation and examples with these new parameters first. I'll probably do that tomorrow.

**Comment by ReeceGoding** [comment]
@erikdarlingdata All done! Feel free to merge.

**Pull request merged**
